name: cima_box

description: "A new Flutter project."
publish_to: 'none' 



version: 1.0.1+2

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  dio: ^5.4.0
  cached_network_image: ^3.3.1
  url_launcher: ^6.2.4
  http: ^1.2.0
  encrypt: ^5.0.3
  better_player_plus:
  wakelock_plus: ^1.2.0
  ffmpeg_kit_flutter_new_https: ^2.1.0
  permission_handler: ^12.0.1
  path_provider: ^2.1.5
  open_file: ^3.5.11
  awesome_notifications: ^0.10.0
  flutter_downloader: ^1.12.0
  crypto: ^3.0.3
  screen_brightness: ^0.2.1
  flutter_volume_controller:
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  google_sign_in: ^6.1.6
  animated_text_kit: ^4.2.2
  unity_ads_plugin: ^0.3.28
  package_info_plus:


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  change_app_package_name: ^1.5.0

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/icon.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
